// Darshil Patel d.p.
//Programming - Rock, Paper, Scissor Game d.p.
//05/16/2019 d.p.
import java.util.Random;
// imorting random from java as we need it for computer choice d.p.
import java.util.Scanner;
// importing scanner from java as we need it for user choice d.p.
public class gameOne {
	public static void main (String [] args) {
		Random choice = new Random();
		// making a randomizer for computer choice d.p.
		Scanner input = new Scanner(System.in);
		// making a input for user choice
		int userDec;
		// making userDec int as we only need whole number d.p.
		int compDec;
		// makinf compDec int as we only need whole number d.p.

		//----------------------------------------------------------------------------- d.p.

		System.out.println("Please select a number from below");
		//Asking user to input a number for thier choice d.p.
		System.out.println("0: Rock");
		// input 0 for rock d.p.
		System.out.println("1: Paper");
		//input 1 for paper d.p.
		System.out.println("2: Scissor");
		//input 2 for scissor d.p.

		//----------------------------------------------------------------------------- d.p.

		userDec= input.nextInt();
		// taking input from user d.p.
		compDec= choice.nextInt(3);
		// keeping randomizer only first 3 number as other wouldnt be useful d.p.

		//----------------------------------------------------------------------------- d.p.

		//INVALID CHOICE d.p.
		if (userDec < 0 || userDec > 2)
			// this is declaring that if number is out of bounds end the game d.p.
		{
			System.out.println("You have Selected Invalid Choices, GoodBye!!");
			// prints out you have selected invlid choice d.p.
			System.exit(0);
			// exit the game d.p.
		}

		//INVALID CHOISE d.p.

		//----------------------------------------------------------------------------- d.p.

		//NUMBERS ARE SAME d.p.
		if (userDec == compDec)
		// this is declaring that if number are the same, display tied and end the game d.p.
		{
			if (userDec == 0)
			// case where both chooses rock d.p.
			{
				System.out.println("You have both Selected Rock, GoodBye!!");
			}
			else if (userDec == 1)
			// case where both chooses paper d.p.
			{
				System.out.println("You have both Selected Paper, GoodBye!!");
			}
			else
			// case where both chooses scissor d.p.
			{
				System.out.println("You have both Selected Scissor, GoodBye!!");
			}
			System.exit(0);
			// exit the game d.p.

		}
		//NUMBERS ARE SAME d.p.

		//----------------------------------------------------------------------------- d.p.

		//USER CHOSES ROCK d.p.
		if (userDec == 0 )
		// this shows what happes when usr choses rock d.p.
		{
			if (compDec == 1)
			// this shows what happens when computer choose paper d.p.
			{
				System.out.println("You choose rock, while computer choose paper. COMPUTER WINS!!");
			}
			else if (compDec == 2)
			// this shows what happens when computer choose scissor d.p.
			{
				System.out.println("You choose rock, while computer choose Scissor. YOU WIN!!");
			}
		}

		//USER CHOSES ROCK d.p.

		//----------------------------------------------------------------------------- d.p.

		//USER CHOSES PAPER d.p.
		else if (userDec == 1 )
		// this shows what happens when user chooses paper d.p.
		{
			if (compDec == 0)
			// this shows what happens when computer chooses rock d.p.
			{
				System.out.println("You choose paper, while computer choose rock. YOU WINS!!");
			}
			else if (compDec == 2)
			// this shows what happens when computer chooses scissor d.p.
			{
				System.out.println("You choose paper , while computer choose Scissor. COMPUTER WIN!!");
			}
		}
		//USER CHOSES PAPER d.p.

		//----------------------------------------------------------------------------- d.p.

		//USER CHOSES SCISSOR d.p.
		else if (userDec == 2 )
		// this shows what happens when user chooses scissor d.p.
		{
			if (compDec == 0)
			// this shows what happen when computer chooses rock d.p.
			{
				System.out.println("You choose scissor, while computer choose rock. COMPUTER WINS!!");
			}
			else if (compDec == 1)
			// this shows what happens when computer paper d.p.
			{
				System.out.println("You choose scissor, while computer choose paper. YOU WIN!!");
			}
		}
		//USER CHOSES SCISSOR d.p.

		//----------------------------------------------------------------------------- d.p.
	}
}


/*
* We need to use randamizor in order for the program to work and to play agaist computer
* We can set random amount to 0,1,2 and set them = to rock, paper and scissor
* We can ask user for inpuut either 0,1,2 which are rock paper and scirssor and match it against random generated by computer to see if what the resut can be
* if statment will be used for this, as we can set varity of condition to declare winner, looser or a tie. \
* we can also use swtich as well to make this work but we will use if
* we will declaore both as an int as we need a whole number
*/